env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_STABLE=1.28.0
    - RUST_NIGHTLY=nightly-2018-07-07
    - RUST_RUSTFMT=0.99.2
    - RUST_CLIPPY=0.0.212
os:
  - linux
  - osx
language: rust
rust:
  - 1.28.0
  - nightly-2018-07-07
sudo: false
cache:
  cargo: true
before_script:
  - if ! cargo prune --version | grep -q "0.1.8"; then
      cargo install cargo-prune --version="0.1.8" --force;
    fi
  - if [ "${TRAVIS_RUST_VERSION}" = "$RUST_NIGHTLY" ]; then
      cargo install --version="$RUST_RUSTFMT" --force rustfmt-nightly;
      cargo install --version="$RUST_CLIPPY" --force clippy;
    fi
script:
  - if [ "${TRAVIS_RUST_VERSION}" = "$RUST_STABLE" ]; then
        (
            set -x;
            cargo test --verbose --release --no-default-features
        );
    elif [ "${TRAVIS_OS_NAME}" = linux ]; then
        (
            set -x;
            cargo fmt -- --check &&
            cargo clippy --profile=test -- -D warnings
        )
    fi
before_cache:
  - cargo prune
