[package]
name = "p2p"
version = "0.4.6"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]

[dependencies]
lazy_static = "*"
tokio-io = "*"
tokio-core = "*"
futures = "*"
rust_sodium = "*"
get_if_addrs = "*"
unwrap = "*"
rand = "*"
bytes = "*"
net2 = "*"
net-literals = "*"
bincode = "*"
future-utils = "0.4.0"
serde = "*"
serde_derive = "*"
env_logger = "*"
void = "*"
log = "*"
quick-error = "*"
igd = "*"
tokio-shared-udp-socket = "0.5.0"
maplit = "*"
docopt = "*"

