[package]
authors = ["ustulation <ustulation@gmail.com>"]
description = "NAT Traversal for P2P communication"
documentation = "https://docs.rs/p2p/"
license = "GPL-3.0"
name = "p2p"
readme = "README.md"
repository = "https://github.com/ustulation/p2p"
version = "0.4.3"

[dependencies]
bincode = "~1.0.0-alpha6"
byteorder = "~1.0.0"
log = "~0.3.7"
mio = "~0.6.6"
net2 = "~0.2.27"
quick-error = "~1.1.0"
rand = "~0.3.15"
rust_sodium = "~0.1.2"
serde = "~0.9.12"
serde_derive = "~0.9.12"

[dev-dependencies]
serde_json = "~0.9.9"
unwrap = "~1.1.0"
