[package]
authors = ["ustulation <ustulation@gmail.com>"]
description = "NAT Traversal for P2P communication"
license = "GPL-3.0"
name = "p2p"
readme = "README.md"
repository = "https://github.com/ustulation/p2p"
version = "0.3.3"

[dependencies]
bincode = "~1.0.0-alpha2"
byteorder = "~1.0.0"
log = "~0.3.6"
mio = "~0.6.4"
net2 = "~0.2.26"
quick-error = "~1.1.0"
rand = "~0.3.15"
rust_sodium = "~0.1.2"
serde = "~0.9.7"
serde_derive = "~0.9.7"

[dev-dependencies]
serde_json = "~0.9.7"
unwrap = "~1.1.0"
