[package]
authors = [
    "ustulation <ustulation@gmail.com>",
    "Andrew Cann <shum@canndrew.org>",
    "Povilas Balciunas <balciunas90@gmail.com>",
]
name = "p2p"
version = "0.4.6"

[dependencies]
bincode = "~0.9.2"
bytes = "~0.4.5"
docopt = "~0.8.1"
env_logger = "~0.4.3"
future-utils = "~0.6.0"
futures = "~0.1.17"
get_if_addrs = "~0.4"
igd = "~0.6"
log = "~0.3.8"
maplit = "~1.0.1"
net-literals = "~0.1"
net2 = "~0.2.31"
podio = "=0.1.5"
quick-error = "~1.2"
rand = "~0.3.18"
rust_sodium = "~0.5"
serde = "~1.0"
serde_derive = "~1.0"
tokio-core = "~0.1.10"
tokio-io = "~0.1.3"
tokio-shared-udp-socket = "~0.5.1"
unwrap = "~1.1"
void = "~1.0"
zip = "=0.2.6"
