[package]
name = "p2p"
version = "0.4.6"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]

[dependencies]
lazy_static = "~0.2.9"
tokio-io = "~0.1.3"
tokio-core = "~0.1.10"
futures = "~0.1.17"
rust_sodium = "~0.5"
get_if_addrs = "~0.4"
unwrap = "~1.1"
rand = "~0.3.18"
bytes = "~0.4.5"
net2 = "~0.2.31"
net-literals = "~0.1"
bincode = "~0.9.2"
future-utils = "~0.6.0"
serde = "~1.0"
serde_derive = "~1.0"
env_logger = "~0.4.3"
void = "~1.0"
log = "~0.3.8"
quick-error = "~1.2"
igd = "~0.6"
tokio-shared-udp-socket = "~0.5.1"
maplit = "~1.0"
docopt = "~0.8.1"

